### ISSUE TITLE
Add silent printer to allow suppressing command echoing

### ISSUE THREAD

**Issue by piotrmurach** [piotrmurach/tty-command#1]
Provide option for `TTY::Command.new` to suppress output logging.

**Comment by gurgeous** [comment]
It's probably also worth considering what happens in the common case here. Often these scripts end up running something like 50 commands in a row, including many that don't output anything. I wonder if we could make the output a bit quieter in general? Like only include logging if requested, or if there is actual output to display.

**Comment by piotrmurach** [comment]
We could investigate different logging levels, or even rely on the Ruby standard logger to implement some of this. Also, we could provide different printer that may just show dot/tick when successful, kind of like rspec does with dots vs documentation formatters.

**Comment by piotrmurach** [comment]
Added rspec like progress printer.

**Comment by piotrmurach** [comment]
Added `:null` printer type which won't output anything, this is as silent as it gets.
