### ISSUE TITLE
Using symbol as command name

### ISSUE THREAD

**Issue by piotrmurach** [piotrmurach/tty-command#10]
> Any reason to use symbols vs. strings for the command name? Sadly some commands have spaces in them...

**Comment by piotrmurach** [comment]
You can use both symbol & string, makes no difference. The reason why I provided the examples this way is simply a stage setup for more ruby like syntax. I was intending to add ability to basically run `cmd.ls "-la"` and the command just do what is intended. Agree it won't work in a lot of cases given complex arguments or executables but it is a nice Ruby-like way to run simple stuff if someone needs to.

**Comment by gurgeous** [comment]
OK, glad to hear that's supported. Might be worth changing the initial examples to something a bit more script-like, though.

**Comment by piotrmurach** [comment]
Agree, in usage section we may provide simple string example(s) and in `execute` part show more possibilities. PR welcome!

**Comment by gurgeous** [comment]
Let's close this and create a new issue that's specific to README
