### ISSUE TITLE
Documentation on how to handle STDIN?

### ISSUE THREAD

**Issue by robotex82** [piotrmurach/tty-command#24]
Hi,

I have a question regarding the input stream. Assume I have a cli program, that first asks for an email address and then asks for a password via STDIN. How can I handle this situation?

I tried something like this, but I am not able to split the input, so it inputs the email address first, and then the password.

    TTY::Command.new.run("my_cli_program", "login", in: StringIO.new("username@example.com\r\npassword")).out

Any clues?

Many thanks!

Best regards,
Roberto

**Comment by robotex82** [comment]
After some experimentation, I solved it like this:

    in_stream = StringIO.new
    in_stream.puts "username@example.com"
    in_stream.puts "password"
    in_stream.rewind

    TTY::Command.new.run("my_cli_program", "login", in: in_stream).out

**Comment by robotex82** [comment]
Added pull request #25

**Comment by piotrmurach** [comment]
Hi Roberto,

Thanks for using the library.

This gem uses `spawn` under the covers and hence supports all of its parameters [see](https://ruby-doc.org/core-2.2.0/Process.html#method-c-spawn).
