### ISSUE TITLE
Mutex

### ISSUE THREAD

**Issue by nate** [piotrmurach/tty-command#35]
I don't think this mutex does anything and I can't figure out the original intention.

https://github.com/piotrmurach/tty-command/blob/master/lib/tty/command.rb#L171-L174

Thoughts?

**Comment by piotrmurach** [comment]
Thanks for using the library! The original intention probably got lost during refactorings :smile: Do you fancy PR? I would move it up to initialize for the time being. In future, I'm thinking of adding parallel runner that may require multi threading support.

**Comment by nate** [comment]
Sorry I'm just getting to this now. I'm not actually using the library but I was checking out the code. Looks like you've got it handled!
