### ISSUE TITLE
Modified command ran when it contains special characters

### ISSUE THREAD

**Issue by thisismydesign** [piotrmurach/tty-command#38]
Hi,

I ran into the issue that I cannot execute the following command when passing the parameters one by one:
`git for-each-ref --format='%(refname)' refs/heads/`

Because it tries to run this command instead: `git for-each-ref '--format='%(refname)''%(refname)''' refs/heads/`

See:
```
require 'tty-command'
cmd = TTY::Command.new
cmd.run(*['git', 'for-each-ref', "--format='%(refname)'", 'refs/heads/'])
```

A possible workaround is to do this:
`cmd.run("git for-each-ref --format='%(refname)' refs/heads/")`

**Comment by piotrmurach** [comment]
Thanks for reporting this! I've removed self-baked solution for Ruby standard lib which correctly escapes arguments and makes multiple arguments work fine.

**Comment by thisismydesign** [comment]
Thanks for the quick fix :)
