### ISSUE TITLE
Are you supposed to always use `rescue TTY::Command::ExitError`?

### ISSUE THREAD

**Issue by revolter** [piotrmurach/tty-command#40]
Is there a case in which a command doesn't succeeds, but also doesn't throw `TTY::Command::ExitError`?
If not, does this mean that you're supposed to always enclose the `run()` in `begin ... recue TTY::Command::ExitError`?
If yes, should this be mentioned in the `README`?

**Comment by jrochkind** [comment]
https://github.com/piotrmurach/tty-command#22-run
