### ISSUE TITLE
Ability to turn off warning when no pseudo terminal is found

### ISSUE THREAD

**Issue by thisismydesign** [piotrmurach/tty-command#45]
Hi,

I've noticed that the following message is printed when using the `pty: true` option on Windows:
`Requested PTY device but the system doesn't support it.` This makes sense and the graceful fallback mentioned in the readme happens.

However the message is
- printed even if `TTY::Command` is used with no output
- printed as a plain line and is therefore out of place if `TTY::Command` is used with `pretty` or custom output
- sometimes simply expected and unwanted

Therefore it'd be great to have an option to turn off this message.

**Comment by piotrmurach** [comment]
Agree. I would suggest `verbose` option which is turned on by default? The warning could be expanded to advise a user that they need to disable this flag in order for the message to go. Can you cook up a PR?
