### ISSUE TITLE
Remove successful execution logging

### ISSUE THREAD

**Issue by piotrmurach** [piotrmurach/tty-command#8]
> I think you could probably ditch the with exit status 0 (successful) and only log failures. That will make them stand out more, I think. Or at least make successful use the same color as the rest of the line.

**Comment by gurgeous** [comment]
Want a PR for this?

**Comment by piotrmurach** [comment]
I prefer to be notified of execution status regardless, don't really see the failure as special case. Also I'm a stickler for consistency :) Therefore, I would probably leave it as is. However, having said that I think we may provide different printers, one with no-frills implementation?

**Comment by gurgeous** [comment]
That sounds fine. I can picture a very quiet printer... :)

**Comment by piotrmurach** [comment]
I will abstract away the common behaviour for printer and then we can provide few versions including very quiet one :)

**Comment by piotrmurach** [comment]
I've abstracted away printers and provided `:printer` option for specifying either printer name or class. Any other printers welcome!

**Comment by gurgeous** [comment]
At this point this is the same as issue #1, so let's close.
